package ru.bell.Controller;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class DBConnection extends Thread {

    public void run() {
        try (Connection connection = DriverManager.getConnection(DBConfig.Connection.URLHOST, DBConfig.Connection.USERNAME, DBConfig.Connection.PASSWORD);
             PreparedStatement ps = connection.prepareStatement(
                     "SELECT 1 FROM pg_database WHERE datname = ?")) {
            ps.setString(1, "leasing");
            ResultSet rs = ps.executeQuery();
            if (!rs.next()) {
                try (Statement stmt = connection.createStatement()) {
                    stmt.executeUpdate("CREATE DATABASE leasing");
                    System.out.println("БД leasing создана!");
                }
            }
            createTableIfNotExists();
        } catch (Exception e) { e.printStackTrace();
            System.out.println("Соединение с сервером не установлено.");
        }
    }

    public void createTableIfNotExists() {
        try (Connection connection = DriverManager.getConnection(DBConfig.Connection.URL, DBConfig.Connection.USERNAME,
                DBConfig.Connection.PASSWORD)) {
            Statement statement = connection.createStatement();
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS clients (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        passport VARCHAR(12) UNIQUE NOT NULL,
                        telephone VARCHAR(20) UNIQUE NOT NULL);""");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS cars (
                        VIN VARCHAR(255) PRIMARY KEY NOT NULL,
                        brand VARCHAR(255),
                        model VARCHAR(255),
                        yearOfRelease INTEGER,
                        cost numeric NOT NULL,
                        isAvailable BOOLEAN);""");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS payments (
                        paymentsids VARCHAR(500),
                        contractId BIGINT NOT NULL,
                        amount NUMERIC NOT NULL,
                        notPaid VARCHAR(500),
                        PRIMARY KEY (paymentsids, contractId));""");
            System.out.println("База данных с таблицами загружена!");
        } catch (Exception e) {
            System.out.println("Базы данных не существует");
        }
    }
}