spring.liquibase.enabled=false

spring.liquibase.show-summary=true
spring.liquibase.show-banner=true
logging.level.liquibase=INFO

url=jdbc:postgresql://localhost:5432/leasing
username=root
password=123
driver=org.postgresql.Driver

# Liquibase settings
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
defaultSchemaName=public
logLevel=info